# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.5-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/api

    steps:
      - checkout

      # Install Composer
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"


      # Download and cache dependencies

      - run:
          name: Display PHP information
          command: |
            php -v
            php composer.phar --version

      - run:
          name: Install project dependencies
          command: php composer.phar install

      test:
        override:
          - cd application/tests && ~/api/vendor/bin/phpunit

      - run:
          name: Prepare Unit Test
          command: |
            phpunit --version
            #~/api/vendor/bin/phpunit --version
            #cd application/tests

      # run tests!
      - run:
           phpunit controllers/unit_test.php
          #~/api/vendor/bin/phpunit controllers/unit_test.php
