# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
            php composer.phar self-update
            sudo mv composer.phar /usr/local/bin/composer

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist
      - run: composer global require phpunit/phpunit

      
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run:
          name: Run Unit Test
          command: |
            cd application/tests
            ~/repo/vendor/bin/phpunit --no-coverage 
      
      - add_ssh_keys:
          fingerprints:
            - "60:a4:59:d0:38:2b:c3:00:bf:a3:b8:63:9d:ab:7c:a0"
      - deploy:
          name: Deploy Over SSH
          #command: rsync -e "ssh -o StrictHostKeyChecking=no" -arvc --exclude .git ~/repo/ ubuntu@ec2-18-206-57-23.compute-1.amazonaws.com:~/repo
          command: rsync -e "ssh -o StrictHostKeyChecking=no" -arvc --exclude .git ~/repo/ ubuntu@ec2-18-206-57-23.compute-1.amazonaws.com:/var/www/html/api-chatbot

      - deploy:
          name: Deploy .htaccess Over SSH
          command: scp  ~/repo/.htaccess_deploy ubuntu@ec2-18-206-57-23.compute-1.amazonaws.com:/var/www/html/api-chatbot/.htaccess

      - deploy:
          name: Deploy config  Over SSH
          command: scp  ~/repo/config_deploy.php ubuntu@ec2-18-206-57-23.compute-1.amazonaws.com:/var/www/html/api-chatbot/application/config/config.php
